server:
  port: 8765

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9999/oauth/token_key
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: oauth2-server
          uri: http://localhost:9999
          predicates:
            - Path=/oauth/**
        - id: auth-service
          uri: http://localhost:9999
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: student-service
          uri: lb://studentms
          predicates:
            - Path=/api/students/**
          filters:
            - StripPrefix=1
        - id: fee-management-service
          uri: lb://fee-management-ms
          predicates:
            - Path=/api/fees/**
          filters:
            - StripPrefix=1
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

jwt:
  secret: eduexcellence-jwt-secret-key

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
